pipeline {
    agent any

    triggers { 
        // No SCM polling, no cron -> only manual trigger
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/<your-username>/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'python3 -m venv venv'
                    sh './venv/bin/pip3 install --upgrade pip'
                    sh './venv/bin/pip3 install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh './venv/bin/pytest --junitxml=messaging_app/report.xml'
                }
            }
            post {
                always {
                    junit 'messaging_app/report.xml'
                }
            }
        }
    }
}
