#!/usr/bin/env python3
"""Test fixtures for Github org client tests."""

# Test payload for organization
org_payload = {
    "login": "google",
    "id": 1342004,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
    "url": "https://api.github.com/orgs/google",
    "repos_url": "https://api.github.com/orgs/google/repos",
    "events_url": "https://api.github.com/orgs/google/events",
    "hooks_url": "https://api.github.com/orgs/google/hooks",
    "issues_url": "https://api.github.com/orgs/google/issues",
    "members_url": "https://api.github.com/orgs/google/members{/member}",
    "public_members_url": "https://api.github.com/orgs/google/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
    "description": "Google ❤️ Open Source",
    "name": "Google",
    "company": None,
    "blog": "https://opensource.google.com/",
    "location": None,
    "email": "opensource@google.com",
    "twitter_username": None,
    "is_verified": True,
    "has_organization_projects": True,
    "has_repository_projects": True,
    "public_repos": 983,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "html_url": "https://github.com/google",
    "created_at": "2012-01-18T01:30:18Z",
    "updated_at": "2019-11-06T19:26:26Z",
    "type": "Organization"
}

# Test payload for repositories
repos_payload = [
    {
        "id": 2325298,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMzI1Mjk4",
        "name": "episodes.dart",
        "full_name": "google/episodes.dart",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/google",
            "html_url": "https://github.com/google",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/google/episodes.dart",
        "description": "A framework for timing performance",
        "fork": False,
        "url": "https://api.github.com/repos/google/episodes.dart",
        "archive_url": "https://api.github.com/repos/google/episodes.dart/{archive_format}{/ref}",
        "assignees_url": "https://api.github.com/repos/google/episodes.dart/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/google/episodes.dart/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/google/episodes.dart/branches{/branch}",
        "collaborators_url": "https://api.github.com/repos/google/episodes.dart/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/google/episodes.dart/comments{/number}",
        "commits_url": "https://api.github.com/repos/google/episodes.dart/commits{/sha}",
        "compare_url": "https://api.github.com/repos/google/episodes.dart/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/google/episodes.dart/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/google/episodes.dart/contributors",
        "created_at": "2011-09-06T09:13:39Z",
        "default_branch": "master",
        "deployments_url": "https://api.github.com/repos/google/episodes.dart/deployments",
        "downloads_url": "https://api.github.com/repos/google/episodes.dart/downloads",
        "events_url": "https://api.github.com/repos/google/episodes.dart/events",
        "forks": 22,
        "forks_count": 22,
        "forks_url": "https://api.github.com/repos/google/episodes.dart/forks",
        "git_commits_url": "https://api.github.com/repos/google/episodes.dart/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/episodes.dart/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/episodes.dart/git/tags{/sha}",
        "git_url": "git://github.com/google/episodes.dart.git",
        "has_downloads": True,
        "has_issues": True,
        "has_pages": False,
        "has_projects": True,
        "has_wiki": True,
        "homepage": None,
        "hooks_url": "https://api.github.com/repos/google/episodes.dart/hooks",
        "issue_comment_url": "https://api.github.com/repos/google/episodes.dart/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/google/episodes.dart/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/google/episodes.dart/issues{/number}",
        "keys_url": "https://api.github.com/repos/google/episodes.dart/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/google/episodes.dart/labels{/name}",
        "language": "Dart",
        "languages_url": "https://api.github.com/repos/google/episodes.dart/languages",
        "license": {
            "key": "bsd-3-clause",
            "name": "BSD 3-Clause \"New\" or \"Revised\" License",
            "spdx_id": "BSD-3-Clause",
            "url": "https://api.github.com/licenses/bsd-3-clause",
            "node_id": "MDc6TGljZW5zZW5vZGVfaWQ="
        },
        "merges_url": "https://api.github.com/repos/google/episodes.dart/merges",
        "milestones_url": "https://api.github.com/repos/google/episodes.dart/milestones{/number}",
        "mirror_url": None,
        "name": "episodes.dart",
        "notifications_url": "https://api.github.com/repos/google/episodes.dart/notifications{/since}",
        "open_issues": 0,
        "open_issues_count": 0,
        "pulls_url": "https://api.github.com/repos/google/episodes.dart/pulls{/number}",
        "pushed_at": "2014-06-03T20:00:30Z",
        "releases_url": "https://api.github.com/repos/google/episodes.dart/releases{/id}",
        "size": 191,
        "ssh_url": "git@github.com:google/episodes.dart.git",
        "stargazers_count": 12,
        "stargazers_url": "https://api.github.com/repos/google/episodes.dart/stargazers",
        "statuses_url": "https://api.github.com/repos/google/episodes.dart/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/google/episodes.dart/subscribers",
        "subscription_url": "https://api.github.com/repos/google/episodes.dart/subscription",
        "tags_url": "https://api.github.com/repos/google/episodes.dart/tags",
        "teams_url": "https://api.github.com/repos/google/episodes.dart/teams",
        "trees_url": "https://api.github.com/repos/google/episodes.dart/git/trees{/sha}",
        "updated_at": "2019-09-23T11:53:58Z",
        "url": "https://api.github.com/repos/google/episodes.dart",
        "watchers": 12,
        "watchers_count": 12
    },
    {
        "id": 3248507,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMjQ4NTA3",
        "name": "cpp-netlib",
        "full_name": "google/cpp-netlib",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/google",
            "html_url": "https://github.com/google",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/google/cpp-netlib",
        "description": "The C++ Network Library Project",
        "fork": True,
        "url": "https://api.github.com/repos/google/cpp-netlib",
        "archive_url": "https://api.github.com/repos/google/cpp-netlib/{archive_format}{/ref}",
        "assignees_url": "https://api.github.com/repos/google/cpp-netlib/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/google/cpp-netlib/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/google/cpp-netlib/branches{/branch}",
        "collaborators_url": "https://api.github.com/repos/google/cpp-netlib/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/google/cpp-netlib/comments{/number}",
        "commits_url": "https://api.github.com/repos/google/cpp-netlib/commits{/sha}",
        "compare_url": "https://api.github.com/repos/google/cpp-netlib/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/google/cpp-netlib/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/google/cpp-netlib/contributors",
        "created_at": "2012-01-10T09:47:30Z",
        "default_branch": "master",
        "deployments_url": "https://api.github.com/repos/google/cpp-netlib/deployments",
        "downloads_url": "https://api.github.com/repos/google/cpp-netlib/downloads",
        "events_url": "https://api.github.com/repos/google/cpp-netlib/events",
        "forks": 26,
        "forks_count": 26,
        "forks_url": "https://api.github.com/repos/google/cpp-netlib/forks",
        "git_commits_url": "https://api.github.com/repos/google/cpp-netlib/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/cpp-netlib/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/cpp-netlib/git/tags{/sha}",
        "git_url": "git://github.com/google/cpp-netlib.git",
        "has_downloads": True,
        "has_issues": False,
        "has_pages": False,
        "has_projects": True,
        "has_wiki": True,
        "homepage": "http://cpp-netlib.github.com/",
        "hooks_url": "https://api.github.com/repos/google/cpp-netlib/hooks",
        "issue_comment_url": "https://api.github.com/repos/google/cpp-netlib/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/google/cpp-netlib/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/google/cpp-netlib/issues{/number}",
        "keys_url": "https://api.github.com/repos/google/cpp-netlib/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/google/cpp-netlib/labels{/name}",
        "language": "C++",
        "languages_url": "https://api.github.com/repos/google/cpp-netlib/languages",
        "license": {
            "key": "bsl-1.0",
            "name": "Boost Software License 1.0",
            "spdx_id": "BSL-1.0",
            "url": "https://api.github.com/licenses/bsl-1.0",
            "node_id": "MDc6TGljZW5zZW5vZGVfaWQ="
        },
        "merges_url": "https://api.github.com/repos/google/cpp-netlib/merges",
        "milestones_url": "https://api.github.com/repos/google/cpp-netlib/milestones{/number}",
        "mirror_url": None,
        "name": "cpp-netlib",
        "notifications_url": "https://api.github.com/repos/google/cpp-netlib/notifications{/since}",
        "open_issues": 0,
        "open_issues_count": 0,
        "pulls_url": "https://api.github.com/repos/google/cpp-netlib/pulls{/number}",
        "pushed_at": "2014-01-13T17:32:45Z",
        "releases_url": "https://api.github.com/repos/google/cpp-netlib/releases{/id}",
        "size": 1831,
        "ssh_url": "git@github.com:google/cpp-netlib.git",
        "stargazers_count": 30,
        "stargazers_url": "https://api.github.com/repos/google/cpp-netlib/stargazers",
        "statuses_url": "https://api.github.com/repos/google/cpp-netlib/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/google/cpp-netlib/subscribers",
        "subscription_url": "https://api.github.com/repos/google/cpp-netlib/subscription",
        "tags_url": "https://api.github.com/repos/google/cpp-netlib/tags",
        "teams_url": "https://api.github.com/repos/google/cpp-netlib/teams",
        "trees_url": "https://api.github.com/repos/google/cpp-netlib/git/trees{/sha}",
        "updated_at": "2019-11-15T22:22:16Z",
        "url": "https://api.github.com/repos/google/cpp-netlib",
        "watchers": 30,
        "watchers_count": 30
    }
]

# Expected repositories list
expected_repos = ["episodes.dart", "cpp-netlib"]

# Expected Apache 2.0 repositories (none in the test data)
apache2_repos = []
